// src/constants/countryOptions.js

export const countryOptions = [
    { label: 'Afghanistan', value: 'AFGHANISTAN' },
    { label: 'Albania', value: 'ALBANIA' },
    { label: 'Algeria', value: 'ALGERIA' },
    { label: 'Angola', value: 'ANGOLA' },
    { label: 'Argentina', value: 'ARGENTINA' },
    { label: 'Australia', value: 'AUSTRALIA' },
    { label: 'Austria', value: 'AUSTRIA' },
    { label: 'Bahamas', value: 'BAHAMAS' },
    { label: 'Bangladesh', value: 'BANGLADESH' },
    { label: 'Belgium', value: 'BELGIUM' },
    { label: 'Bermuda', value: 'BERMUDA' },
    { label: 'Brazil', value: 'BRAZIL' },
    { label: 'Bulgaria', value: 'BULGARIA' },
    { label: 'Burkina Faso', value: 'BURKINA_FASO' },
    { label: 'Cambodia', value: 'CAMBODIA' },
    { label: 'Cameroon', value: 'CAMEROON' },
    { label: 'Canada', value: 'CANADA' },
    { label: 'Cayman Islands', value: 'CAYMAN_ISLANDS' },
    { label: 'Chile', value: 'CHILE' },
    { label: 'China', value: 'CHINA' },
    { label: 'Colombia', value: 'COLOMBIA' },
    { label: 'Croatia', value: 'CROATIA' },
    { label: 'Czech Republic', value: 'CZECH_REPUBLIC' },
    { label: 'Denmark', value: 'DENMARK' },
    { label: 'Dominican Republic', value: 'DOMINICAN_REPUBLIC' },
    { label: 'East Germany', value: 'EAST_GERMANY' },
    { label: 'Ecuador', value: 'ECUADOR' },
    { label: 'Egypt', value: 'EGYPT' },
    { label: 'Ethiopia', value: 'ETHIOPIA' },
    { label: 'Finland', value: 'FINLAND' },
    { label: 'France', value: 'FRANCE' },
    { label: 'Georgia', value: 'GEORGIA' },
    { label: 'Germany', value: 'GERMANY' },
    { label: 'Ghana', value: 'GHANA' },
    { label: 'Greece', value: 'GREECE' },
    { label: 'Guatemala', value: 'GUATEMALA' },
    { label: 'Hong Kong', value: 'HONG_KONG' },
    { label: 'Hungary', value: 'HUNGARY' },
    { label: 'Iceland', value: 'ICELAND' },
    { label: 'India', value: 'INDIA' },
    { label: 'Indonesia', value: 'INDONESIA' },
    { label: 'Iran', value: 'IRAN' },
    { label: 'Iraq', value: 'IRAQ' },
    { label: 'Ireland', value: 'IRELAND' },
    { label: 'Israel', value: 'ISRAEL' },
    { label: 'Italy', value: 'ITALY' },
    { label: 'Jamaica', value: 'JAMAICA' },
    { label: 'Japan', value: 'JAPAN' },
    { label: 'Jordan', value: 'JORDAN' },
    { label: 'Kenya', value: 'KENYA' },
    { label: 'Kuwait', value: 'KUWAIT' },
    { label: 'Latvia', value: 'LATVIA' },
    { label: 'Lebanon', value: 'LEBANON' },
    { label: 'Liechtenstein', value: 'LIECHTENSTEIN' },
    { label: 'Lithuania', value: 'LITHUANIA' },
    { label: 'Luxembourg', value: 'LUXEMBOURG' },
    { label: 'Malawi', value: 'MALAWI' },
    { label: 'Malaysia', value: 'MALAYSIA' },
    { label: 'Malta', value: 'MALTA' },
    { label: 'Mauritius', value: 'MAURITIUS' },
    { label: 'Mexico', value: 'MEXICO' },
    { label: 'Montenegro', value: 'MONTENEGRO' },
    { label: 'Morocco', value: 'MOROCCO' },
    { label: 'Mozambique', value: 'MOZAMBIQUE' },
    { label: 'Namibia', value: 'NAMIBIA' },
    { label: 'Nepal', value: 'NEPAL' },
    { label: 'Netherlands', value: 'NETHERLANDS' },
    { label: 'New Zealand', value: 'NEW_ZEALAND' },
    { label: 'Nicaragua', value: 'NICARAGUA' },
    { label: 'Nigeria', value: 'NIGERIA' },
    { label: 'Norway', value: 'NORWAY' },
    { label: 'Pakistan', value: 'PAKISTAN' },
    { label: 'Panama', value: 'PANAMA' },
    { label: 'Paraguay', value: 'PARAGUAY' },
    { label: 'Peru', value: 'PERU' },
    { label: 'Philippines', value: 'PHILIPPINES' },
    { label: 'Poland', value: 'POLAND' },
    { label: 'Portugal', value: 'PORTUGAL' },
    { label: 'Qatar', value: 'QATAR' },
    { label: 'Romania', value: 'ROMANIA' },
    { label: 'Russia', value: 'RUSSIA' },
    { label: 'Saudi Arabia', value: 'SAUDI_ARABIA' },
    { label: 'Senegal', value: 'SENEGAL' },
    { label: 'Serbia', value: 'SERBIA' },
    { label: 'Singapore', value: 'SINGAPORE' },
    { label: 'Slovakia', value: 'SLOVAKIA' },
    { label: 'Slovenia', value: 'SLOVENIA' },
    { label: 'Somalia', value: 'SOMALIA' },
    { label: 'South Africa', value: 'SOUTH_AFRICA' },
    { label: 'South Korea', value: 'SOUTH_KOREA' },
    { label: 'Soviet Union', value: 'SOVIET_UNION' },
    { label: 'Spain', value: 'SPAIN' },
    { label: 'Sri Lanka', value: 'SRI_LANKA' },
    { label: 'Sudan', value: 'SUDAN' },
    { label: 'Sweden', value: 'SWEDEN' },
    { label: 'Switzerland', value: 'SWITZERLAND' },
    { label: 'Syria', value: 'SYRIA' },
    { label: 'Taiwan', value: 'TAIWAN' },
    { label: 'Thailand', value: 'THAILAND' },
    { label: 'Turkey', value: 'TURKEY' },
    { label: 'United Arab Emirates', value: 'UNITED_ARAB_EMIRATES' },
    { label: 'United Kingdom', value: 'UNITED_KINGDOM' },
    { label: 'United States', value: 'UNITED_STATES' },
    { label: 'Uruguay', value: 'URUGUAY' },
    { label: 'Vatican City', value: 'VATICAN_CITY' },
    { label: 'Venezuela', value: 'VENEZUELA' },
    { label: 'Vietnam', value: 'VIETNAM' },
    { label: 'West Germany', value: 'WEST_GERMANY' },
    { label: 'Zimbabwe', value: 'ZIMBABWE' }
  ];
  