export const genreOptions = [
    { label: 'Action & Adventure', value: 'ACTION_ADVENTURE' },
    { label: 'Anime Features', value: 'ANIME_FEATURES' },
    { label: 'Anime Series', value: 'ANIME_SERIES' },
    { label: 'British TV Shows', value: 'BRITISH_TV_SHOWS' },
    { label: 'Children & Family Movies', value: 'CHILDREN_FAMILY_MOVIES' },
    { label: 'Classic & Cult TV', value: 'CLASSIC_CULT_TV' },
    { label: 'Classic Movies', value: 'CLASSIC_MOVIES' },
    { label: 'Comedies', value: 'COMEDIES' },
    { label: 'Crime TV Shows', value: 'CRIME_TV_SHOWS' },
    { label: 'Cult Movies', value: 'CULT_MOVIES' },
    { label: 'Documentaries', value: 'DOCUMENTARIES' },
    { label: 'Docuseries', value: 'DOCUSERIES' },
    { label: 'Dramas', value: 'DRAMAS' },
    { label: 'Faith & Spirituality', value: 'FAITH_SPIRITUALITY' },
    { label: 'Horror Movies', value: 'HORROR_MOVIES' },
    { label: 'Independent Movies', value: 'INDEPENDENT_MOVIES' },
    { label: 'International Movies', value: 'INTERNATIONAL_MOVIES' },
    { label: 'International TV Shows', value: 'INTERNATIONAL_TV_SHOWS' },
    { label: "Kids' TV", value: 'KIDS_TV' },
    { label: 'Korean TV Shows', value: 'KOREAN_TV_SHOWS' },
    { label: 'LGBTQ Movies', value: 'LGBTQ_MOVIES' },
    { label: 'Movies', value: 'MOVIES' },
    { label: 'Music & Musicals', value: 'MUSIC_MUSICALS' },
    { label: 'Reality TV', value: 'REALITY_TV' },
    { label: 'Romantic Movies', value: 'ROMANTIC_MOVIES' },
    { label: 'Romantic TV Shows', value: 'ROMANTIC_TV_SHOWS' },
    { label: 'Science & Nature TV', value: 'SCIENCE_NATURE_TV' },
    { label: 'Sci-Fi & Fantasy', value: 'SCI_FI_FANTASY' },
    { label: 'Spanish-Language TV Shows', value: 'SPANISH_LANGUAGE_TV_SHOWS' },
    { label: 'Sports Movies', value: 'SPORTS_MOVIES' },
    { label: 'Stand-Up Comedy', value: 'STAND_UP_COMEDY' },
    { label: 'Stand-Up Comedy & Talk Shows', value: 'STAND_UP_COMEDY_TALK_SHOWS' },
    { label: 'Teen TV Shows', value: 'TEEN_TV_SHOWS' },
    { label: 'Thrillers', value: 'THRILLERS' },
    { label: 'TV Action & Adventure', value: 'TV_ACTION_ADVENTURE' },
    { label: 'TV Comedies', value: 'TV_COMEDIES' },
    { label: 'TV Dramas', value: 'TV_DRAMAS' },
    { label: 'TV Horror', value: 'TV_HORROR' },
    { label: 'TV Mysteries', value: 'TV_MYSTERIES' },
    { label: 'TV Sci-Fi & Fantasy', value: 'TV_SCI_FI_FANTASY' },
    { label: 'TV Shows', value: 'TV_SHOWS' },
    { label: 'TV Thrillers', value: 'TV_THRILLERS' }
  ];
  